GET /users HTTP/1.1
Host: localhost:8888

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Za",
    "email": "rezafauzan@gmail.com",
    "password": "test1246"
}

###

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Reza",
    "email": "rezafauzan",
    "password": "test1246"
}

###

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Reza",
    "email": "rezafauzan@gmail.com",
    "password": "test"
}

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Reza Fauzan Adhima",
    "email": "rezafauzan@gmail.com",
    "password": "test1246"
}

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Reza Fauzan",
    "email": "rezafauzan945@gmail.com",
    "password": "rezafauzan945@gmail.com"
}

###

GET /users/0 HTTP/1.1
Host: localhost:8888

###

DELETE /users/0 HTTP/1.1
Host: localhost:8888

###

PATCH /users/0 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "password": "test1246"
}

###

PATCH /users/0 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "rezafauzan945@gmail.com",
    "password": "test1246"
}

###

POST /login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "rezafauzan945@gmail.com",
    "password": "test1246"
}

###

PATCH /users/1 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "password": "test1246"
}