# GET /users HTTP/1.1
# Host: localhost:8888

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Reza Fauzan Adhima",
    "email": "rezafauzan945@gmail.com",
    "password": "rezafauzan945@gmail.com"
}