basePath: /
definitions:
  data.Response:
    properties:
      messages:
        type: string
      responseBody: {}
      success:
        type: boolean
    type: object
host: localhost:8888
info:
  contact: {}
  description: Backend app built with gin swagger
  title: Koda-B6-Backend1
  version: "1.0"
paths:
  /users:
    get:
      description: Get all registered users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Response'
      summary: Get all registered users
      tags:
      - user
swagger: "2.0"
